sudo: required

services:
  - docker

before_install:
- docker pull microsoft/aspnetcore
- docker pull microsoft/aspnetcore-build

script:
- docker run -it -v `pwd`:/sln --workdir /sln microsoft/aspnetcore-build sh build.sh
- docker build -t core-container ./Web